### ISSUE TITLE
userAttributeMappings not getting configured

### ISSUE THREAD

**Issue by ali-mansoor** [jeffwils/grails-spring-security-saml#28]
I am using below configuration which is always empty

          saml:
              userAttributeMappings:
                  username: 'username'

**Comment by irstevenson** [comment]
Hi @ali-mansoor ,

Could you please advise what version you're using? From there we can better attempt to assist.

Thanks!

**Comment by ali-mansoor** [comment]
I am using Grails 3.3.3 and below plugin

    compile "org.grails.plugins:spring-security-core:3.2.1"
    compile "org.grails.plugins:spring-security-saml:3.3.0"
    compile "org.grails.plugins:spring-security-ui:3.1.2"

     saml:
          userAttributeMappings:
              username: 'username'

My Grails application is not loading userAttributeMappings config which I configured in application.yml instead it taking default value

**Comment by valentingoebel** [comment]
I cannot reproduce this issue. Configuring userAttributeMappings works as intended.

I have checked the source code and didn't find anything problem. The grails 3.3.0 update didn't touch that part of the codebase.

Did you correctly configure application.yml? The hierarchy should look like this.

```
grails:
    plugin:
        springsecurity:
            saml:
                userAttributeMappings:
                    username: 'urn:oid:0.9.2342.19200300.100.1.1'
```
