### ISSUE TITLE
Is this plugin still supported?

### ISSUE THREAD

**Issue by RogelioCodes** [jeffwils/grails-spring-security-saml#76]
I am trying to get the app running by following the documentation. It is impossible to get this to compile using the basic configuration provided in the documentation. I know we have to modify some of the values, but in general even once you do that there seems to be a ton of issues. 

| Grails Version: 4.0.3
| JVM Version: 1.8.0_292

**Comment by RogelioCodes** [comment]
For example. I ran into this same issue https://github.com/jeffwils/grails-spring-security-saml/issues/1

Even after configuring the right roles and modifying the necessary files,  I still get the same issue. Nobody ever provided a follow up so I cant even tell if the solution ended up working.

**Comment by valentingoebel** [comment]
I don't know what your error is.

If you refer to
```
Caused by: grails.plugins.exceptions.PluginException: Failed to initialize class [test.TestRole] from plugin [springSecuritySaml] : org/grails/datastore/gorm/GormEntity$Trait$FieldHelper
```

It means the class test.TestRole is missing because the example files were removed in the published jar file.

The version in this repository is 4.0.2. It still works and I am still using it in one application that hasn't been upgraded but it's been such a long time since I've had to configure this plugin from scratch. You can consider it unsupported and you should switch to the one for Grails 5.0.0 because the underlying spring security saml extension has been unsupported since 6 October 2021.

See https://github.com/spring-projects/spring-security-saml

Here is the configuration I am using for 4.0.2:

```
---
grails:
    plugin:
        springsecurity:
            providerNames: ['samlAuthenticationProvider', 'anonymousAuthenticationProvider', 'daoAuthenticationProvider']
            password:
                algorithm: 'bcrypt'
            userLookup:
                userDomainClassName: <package>.User
                authorityJoinClassName: <package>.UserRole
                authoritiesPropertyName: authorities
            authority:
                className: <package>.Role
                groupAuthorityNameField: authorities
            useRoleGroups: true
            saml:
                active: true
                userAttributeMappings:
                    username: 'urn:oid:<oid>'
                userGroupAttribute: 'urn:oid:<oid>'
                afterLoginUrl: '/'
                afterLogoutUrl: '/'
                responseSkew: 60
                maxAuthenticationAge: 604800
                retrieveDatabaseRoles: false
                retrieveDatabaseGroups: true
                autoCreate:
                    active: false
                    key: 'username'
                    assignAuthorities: false
                useLocalRoles: true
                metadata:
                    defaultIdp: '<IDP_ENTITY_ID>'
                    providers:
                        <idp_alias>: 'security/<IDP_METADATA.xml>'
                    url: '/saml/metadata'
                    sp:
                        defaults:
                            local: true
                            securityProfile: 'metaiop'
                            requireArtifactResolveSigned: false
                            requireLogoutRequestSigned: false
                            requireLogoutResponseSigned: false
                            signingKey: 'sso-key'
                            encryptionKey: 'sso-key'
                            tlsKey: 'sso-key'
                keyManager:
                    storeFile: classpath:security/sso-keyStore.jks
                    storePass: ${KEYSTORE_PASS}
                    passwords:
                        sso-key: ${KEYSTORE_PASS}
                    defaultKey: 'sso-key'
```

plus another yml file that overrides the above configuration:

```
    plugin:
        greenmail:
            ports:
                smtp: 8465
            disabled: true
        springsecurity:
            saml:
                userLookup:
                    userDomainClassName: <app-package>.User
                userAttributeMappings:
                    username: 'urn:oid:<oid>'
                metadata:
                    sp:
                        file: 'security/<SP_METADATA>-qa.xml'
                        defaults:
                            entityID: '<SP_ENTITY_ID>'
                            alias: ''<SP_ENTITY_ID>'
                            securityProfile: 'metaiop'
                            signingKey: ''<keystore entry name>'
                            encryptionKey: '<keystore entry name>'
                            tlsKey: '<keystore entry name>'
                keyManager:
                    storeFile: 'classpath:security/keystore.jks'
                    storePass: ${KEYSTORE_PASS}
                    passwords:
                        '<keystore entry name>': ${KEYSTORE_PASS}
                    defaultKey: 'fista-qa'
```

I am still using the same User/Role class from 3 years ago so I don't know if the code generators are producing something unexpected.
